name: CI
on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node (solo si hay package.json)
      - name: Setup Node
        if: ${{ hashFiles('**/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Install deps (Node)
        if: ${{ hashFiles('**/package.json') != '' }}
        run: npm ci --workspaces --if-present
      - name: Lint (si existe script)
        if: ${{ hashFiles('**/package.json') != '' }}
        run: npm run lint --workspaces --if-present || echo "No lint"
      - name: Tests (si existen)
        if: ${{ hashFiles('**/package.json') != '' }}
        run: npm test --workspaces --if-present || echo "No tests"

      # Python (solo si hay pyproject/requirements)
      - name: Setup Python
        if: ${{ hashFiles('**/pyproject.toml') != '' || hashFiles('**/requirements.txt') != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps (Python)
        if: ${{ hashFiles('**/pyproject.toml') != '' || hashFiles('**/requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install ruff pytest || true
      - name: Ruff lint
        if: ${{ hashFiles('**/*.py') != '' }}
        run: ruff check . || true
      - name: Pytests
        if: ${{ hashFiles('**/tests/**/*.py') != '' }}
        run: pytest -q || true
